theme: jekyll-theme-cayman
---
layout: default
title: Welcome to My Data Analytics Portfolio
---
# Welcome
This is my portfolio showcasing data analytics projects.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sayyed Shahid's Portfolio</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Welcome to My Data Analytics Portfolio</h1>
    </header>
    <main>
        <section>
            <h2>About Me</h2>
            <p>Hi, I'm Sayyed Shahid, a data analyst...</p>
        </section>
        <section>
            <h2>Projects</h2>
            <p>Here are some of my data analytics projects...</p>
        </section>
        <section>
            <h2>Contact</h2>
            <p>You can reach me at...</p>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Sayyed Shahid</p>
    </footer>
</body>
</html>
